### PR TITLE
Fix background color

### PR DESCRIPTION
**Pull request by kbarber**
Hi there,

I realise this gem is deprecated, but we've been investigating its usage at Puppetlabs for our own console purposes and we feel that its less intrusive then ansicon. The only problem I have is the preservation of background color really. I've taken the patches from Gordon Thiesfeld and included them in this pull request.

Is there any chance of merging this in and releasing a new gem with this tiny fix? I'd rather avoid a fork or to maintain our own copy just for our own purposes.

Thanks :-).

ken.

### CODE REVIEW

**Comment by luislavena** [comment]
Hello @kbarber 

Did you took a look to my comment on the original issue?

https://github.com/luislavena/win32console/pull/8#issuecomment-510456

> Applying these patches breaks the mouse cursor tests (using the C extension). rake compile and rake test will be enough to see them fail.

Have you worked out that issue?

If so, then I'll merge and release a new gem, but the breakage of that test is not a good sign :wink:

**Comment by kbarber** [comment]
Let me take a look. Thanks :-).
On Apr 10, 2012 1:15 PM, "Luis Lavena" <
reply@reply.github.com>
wrote:

**Comment by kbarber** [comment]
@luislavena okay - I believe thats fixed now. Can you please check it?

Also - anything else you would like me to do?

**Comment by luislavena** [comment]
@kbarber don't think so, looks good. Will merge it on friday and release it over the weekend as I'm a bit overloaded with work tomorrow and Tues.

**Comment by kbarber** [comment]
@luislavena great :-). I'm on Freenode as ken_barber if you need me - usually lurking on #ruby.

**Comment by kbarber** [comment]
Any luck with this @luislavena?

**Comment by luislavena** [comment]
I'm actually going over all my pinned OSS emails today and will get this out in a bit, doing mysql2/rubyinstaller/sqlite3-ruby/rake-compiler and a few others takes some time :wink:

**Comment by luislavena** [comment]
Ok, All good, seems to be working, merging now and wrapping a new release!

**Comment by luislavena** [comment]
@kbarber merged and released as version 1.3.1

Please note that compilation will fail under Ruby 1.9.3 as C90 forbids mixing declaration with code, which is the default option provided to GCC by Ruby `rbconfig`

It will work with Ruby 1.8.7 and 1.9.2.

Feel free to send patches for 1.9.3, I'm not sure if I will be able to tackle the issue myself the following weeks.

Regards.

**Comment by kbarber** [comment]
@luislavena so you are describing a problem in the C code I presume? Let me seem what the team wants to do and get back to you. I think though that 1.9.3 coverage is important, so you may hear from me in another pull request.

Thanks very much for this, I appreciate your efforts and help - we look forward to using your gem. I realise it is deprecated, but like I said we felt that ansicon was a heavy approach for our users and this gem provides a light touch though its stdout interception approach - and avoids external application installation. As facter/puppet is one of these programs people use to install other applications, obviously we are wary of the choices we make when it comes to dependencies.

**Comment by luislavena** [comment]
>  so you are describing a problem in the C code I presume?

Yes, and the C code is compiled when the gem is installed. Attempt to install the gem under a Ruby 1.9.3 greater than p0 will fail.

**Pull request merged**
